# Global settings applied to the whole site.
# “public” is the directory to publish (relative to root of the repo).
# “command” is the build command.

[build]
  publish = "dist"
  command = "npm run build:server"
